version: '3.8'

services:
  db:
    build: ./database
    environment:
      POSTGRES_PASSWORD: aikotoba
    ports:
      - 5432:5432
    volumes:
      - ./data/scored:/data
      # - ./data/output:/data
      - ./postgresdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  app:
    build: ./app

  server:
    build: ./server
    environment:
      RUST_LOG: INFO
      SGBG_PORT: 3000
      SGBG_DB: 'postgresql://postgres:aikotoba@db:5432'
      SGBG_RATE_NUM: 3
      SGBG_RATE_PER: 6
    depends_on:
      - db

  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      # - 443:443
      # - 443:443/udp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - server
